# Generated by Django 5.2.4 on 2025-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
