"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-6!*77m!wllj^5xr(2&#qh$_^2-=ka2gf)=5$kq$g4j8#v3@3&=')

# Paystack secret key
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', 'your-paystack-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'products',
    'messaging',
    'orders'
]

INSTALLED_APPS += [
    'storages',
]

# The order of MIDDLEWARE is important. Here's the recommended order:
MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',  # Compress responses - reduces data transfer by 60%
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Should come before any middleware that can generate responses
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Must be before AuthenticationMiddleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for local development, PostgreSQL for production
USE_POSTGRES = os.environ.get("USE_POSTGRES", "False").lower() == "true"

if USE_POSTGRES:
    # Production: PostgreSQL (Google Cloud SQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'unitradegh',
            'USER': 'postgres',
            'PASSWORD': '@ShadowLeak2020',
            'HOST': '/cloudsql/secure-answer-455906-d6:europe-west1:unitradegh',
            'PORT': 5432,
        }
    }
else:
    # Local Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Google Cloud Storage for media and static files (Production only)
# For local development, use local file storage
USE_GCS = os.environ.get("USE_GCS", "False").lower() == "true"

if USE_GCS:
    # Production: Use Google Cloud Storage
    import json
    from google.oauth2 import service_account

    GS_BUCKET_NAME = os.environ.get("GS_BUCKET_NAME", "unitradegh")

    # Try to get credentials from environment variable first
    service_account_json = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if service_account_json:
        try:
            # If it's a JSON string
            service_account_info = json.loads(service_account_json)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(service_account_info)
        except json.JSONDecodeError:
            # If it's a file path
            GS_CREDENTIALS = service_account.Credentials.from_service_account_file(service_account_json)
    else:
        # Fallback to local credentials file
        credentials_path = os.path.join(BASE_DIR, 'backend', 'credentials.json')
        if os.path.exists(credentials_path):
            GS_CREDENTIALS = service_account.Credentials.from_service_account_file(credentials_path)
        else:
            raise FileNotFoundError("Google Cloud credentials not found. Set USE_GCS=False for local development.")

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_NAME,
                "credentials": GS_CREDENTIALS
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_NAME,
                "credentials": GS_CREDENTIALS
            },
        },
    }

    STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
else:
    # Local Development: Use local file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend (Zoho Mail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@unitradegh.com'
EMAIL_HOST_PASSWORD = '@UniTrade2025'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'support@unitradegh.com'

CSRF_TRUSTED_ORIGINS = [
    'https://unitradegh-backend-946167918479.europe-west1.run.app',
    'https://unitradegh-frontend-946167918479.europe-west1.run.app',
    'https://unitradegh.com',
    'http://localhost:8000',
    'http://localhost:3000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:3000'
]

# CORS settings
# Set to True to allow all origins (not recommended for production)
# For local mobile app testing, set to True
CORS_ALLOW_ALL_ORIGINS = True  # Changed to True for mobile app development

# Allow credentials (cookies, authorization headers, etc.) to be included in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

# List of allowed origins (must match the request origin exactly)
CORS_ALLOWED_ORIGINS = [
    'https://unitradegh-frontend-946167918479.europe-west1.run.app',
    'https://unitradegh.com',
    'http://localhost:3000',
    'http://127.0.0.1:3000'
]

# List of allowed headers for CORS requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-xsrf-token',
    'x-csrf-token',
]

# List of allowed HTTP methods for CORS requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Expose additional headers to the browser
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# Set to True to include the Access-Control-Allow-Credentials header in responses
CORS_ALLOW_CREDENTIALS = True

# Set the maximum age (in seconds) for CORS preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Set to True to allow the browser to include credentials (cookies, etc.) in requests
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read the CSRF cookie
CSRF_USE_SESSIONS = False  # Use cookies for CSRF (not sessions)
CSRF_COOKIE_SAMESITE = 'Lax'  # 'Lax' is a good default for most sites

# Configure session settings
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Zenoph Notify SMS API credentials
ZENOPH_API_KEY = '0e69b046205bf10c11703dc7b4607279a42cb33e96cbb3a62ba7ecc9f5cb97fd'
ZENOPH_SENDER_ID = 'UniTradeGH'
